### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#10]
Si falla el load de userlist o mailist en bootup de mánager, dar la opción de introducir la url de los archivos de datos a mano.

**Comment by vigonz06** [comment]
Casi completado, pero necesitó saber como hacer que load se dirija a la url especificada

**Comment by vigonz06** [comment]
Básicamente lo de mi ultimo comentario, como le digo a load: "oye, que es aquí donde tienes que buscar"?

**Comment by vigonz06** [comment]
No puedo hacer nada mas sin ayuda

**Comment by Jsevillamol** [comment]
```
bool Manager::bootUp()
{
    std::ostringstream mail_file, user_file;
    mail_file << domain << "_mails.txt";
    user_file << domain << "_users.txt";
    if (!mailList.load(mail_file.str())) mailList.load(manual());
    if (!userList.load(user_file.str())) userList.load(manual()) ;
    return true;
}
```

Donde `manual()` es una función tipo string.
He cambiado de nuevo de idea. Ahora ponla en GraphInter, porque recibe input del usuario. 
Lo ideal sería crear otra clase que fuera la interfaz grafica con el admin, pero es mucho trabajo.

**Comment by vigonz06** [comment]
Manual entiendo que devuelve un string con el nombre del archivo donde se encuentren los datos de carga, no?

**Comment by vigonz06** [comment]
O simplemente su nombre?

**Comment by vigonz06** [comment]
manual()
{
      std::string file_name;

```
  entre(file_name);

  return file_name;
```

}

Así he definido manual

**Comment by vigonz06** [comment]
Lo de la nueva clase a mi me parece bien, podría intentar hacerlo en otra branch, pero necesito que me diga que iría ahí, que funciones meter

**Comment by vigonz06** [comment]
Deduzco que aquí irán las funciones que utiliza mánager. Pero hay muchas que usa mánager, que también se necesitan para otros módulos (error, entre, pausa...), por tanto, pongo graphadmin clase derivada de graphinter, o las dejo independientes.
En caso de dejarlas separadas, las funciones que ya están en graphinter que se necesitan en mánager las cojo de ahí, o las redefino en graphadmin?

**Comment by Jsevillamol** [comment]
No te compliques, ponlo todo en GraphInter

**Comment by vigonz06** [comment]
Perfecto

Manual esta bien?

**Comment by vigonz06** [comment]
En cuanto me des el visto bueno a manual cierro esta issue

**Comment by Jsevillamol** [comment]
Tip: pon el [SHA de un commit](https://guides.github.com/features/mastering-markdown/) para llamar la atención sobre el en una issue.

**Comment by vigonz06** [comment]
Es buena idea, y esta bien que me lo digas, porque no se me había ocurrido, aun así, aun no he hecho commit

**Comment by vigonz06** [comment]
La duda que tengo es que el argumento que le pasas a load es el nombre del archivo, no su url, por lo que si el archivo esta en otra carpeta se fastidió, no?

**Comment by vigonz06** [comment]
Supongo que si lo quieres así

Por otra parte se me ocurre definir dos strings en bootUp, y emplear la función enter de graphinter, con lo que nos ahorramos definir manual.
Pensé que no lo querrías asi por ahorrar la referencia a graphinter desde mánager, pero para llamar a manual no te queda otra que hacer referencia a graphinter, por lo que de esa otra forma, usando enter, nos ahorramos definir una funcion

**Comment by Jsevillamol** [comment]
Lo que le pasas como argumento es la URL.
Si solo pones el nombre de archivo, se interpreta que la URL es relativa, pero puedes pasarle una dirección completa.

**Comment by Jsevillamol** [comment]
Reutiliza lo que quieras, por cierto.
Pero que quede claro durante la ejecución qué se le está pidiendo al usuario.

**Comment by vigonz06** [comment]
Vale, por tanto necesito un cout (o enter de graphinter)

**Comment by vigonz06** [comment]
Estoy pensando y creo que si voy a hacer una función bucle que te deje meter la url tantas veces como haga falta mientras no cargue, y mientras metas algo distinto a nada 

String newname

while(!type.load(name) && newname != "")

Cout could not load

Cout enter the file url ((ENTER) for continue

Cin newname

If newname != ""

Name = newname

**Comment by vigonz06** [comment]
Haría dos funciones así en mánager, una para década tipo de load, o bien una sola en list, pero me dijiste que en list no, así que dos en manager

**Comment by vigonz06** [comment]
Mas que nada me interesa meter el bucle porque que pasa si te equivocas al meter la url, si se te baila una letra, u olvida poner una palabra? La has fastidiado, necesitas reiniciar el programa para volver a cargar los archivos, y siempre puedes volver a equivocarte

**Comment by vigonz06** [comment]
Echale un vistazo a mi ultimo commit 6bfb0aa

**Comment by vigonz06** [comment]
Voy publicando la branch de multirecipients

**Comment by vigonz06** [comment]
Cierro esta, si no te gusta lo del bucle, reabrela, y describeme como la quieres
