### ISSUE TITLE
Múltiples destinatarios

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#11]
Para new mail y forward, answer no, ya que no tiene sentido responder a varios usuarios cuando solo uno te ha mandado el mensaje original, para eso esta forward

**Comment by vigonz06** [comment]
Esto lo sitúo al mismo nivel que sfml, es decir, si da tiempo a implementarlo y que funcione perfecto, si no entregamos la versión anterior y apañado.
Con la diferencia de que esto tiene prioridad frente a sfml, ya que esto venia propuesto en el enunciado

**Comment by vigonz06** [comment]
Me la asigno a mi porque así a bote pronto tengo algunas ideas, pero no me sorprendería que en nada necesitara una etiqueta de help wanted

**Comment by vigonz06** [comment]
Últimamente le estoy poniendo help wanted a todo

Tengo un esqueleto, pero da ciertos errores, si bien no son excepciones, no hace lo que tiene que hacer, da errores logicos

**Comment by vigonz06** [comment]
Esto de momento nada, ya que esta en una branch que no he publicado, y que publicaré cuando arreglemos manualy

Pero básicamente un vistazo general, ya que el mail encuentra el primer destinatario, pero no los demás

Apunte: creo que esto refuerza mi teoría de que el fallo de activetray esté en search(), ya que esto también emplea search()

**Comment by vigonz06** [comment]
He implementado unas costillas:

Si no hay asunto se establece automáticamente "no subject"

Controlador para los casos en que el usuario selecciona 0 destinatarios, o pone un destinatario nulo

El controlador que teníamos de que si algo es nulo el mail no se manda esta modificado, y solo salta si esta vacío en body (ya que el de los destinatarios se evalúa mas arriba dentro de la función)

Temas a parte, no he conseguido solventar el problema de que encuentre a un usuario, pero al resto no, tengo que investigar si el fallo esta en mi algoritmo o en el de List::search()

**Comment by vigonz06** [comment]
Apunte: estos últimos cambios están en mi branch de multyrecipients, que aun no he publicado, no los busques en máster que no están ahi

**Comment by vigonz06** [comment]
Publicada, cuando puedas mira a ver como lo ves, por cierto, se siguen añadiendo espacios en blanco en los archivos de guardado de mails y users

**Comment by vigonz06** [comment]
No hace falta que mires el código, simplemente dime si prefieres que mande los mails a los usuarios que encuentre, o que si no los encuentra todos, no se mande el mail

**Comment by Jsevillamol** [comment]
A todos los que encuentre, y que muestre un mensaje por cada uno no encontrado.

**Comment by vigonz06** [comment]
Perfecto

**Comment by vigonz06** [comment]
Te ha gustado como esta? (Si lo has visto)

**Comment by vigonz06** [comment]
Subido (hace un rato), echale un vistazo y dime si te gusta

**Comment by vigonz06** [comment]
Si estas conforme cierro esta issue, yo creo que esta bien

**Comment by Jsevillamol** [comment]
Tiene buena pinta. Cerramos de momento.
