### ISSUE TITLE
Espacios en maillist

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#13]
¿Soy yo o cada vez hay más saltos de línea en maillist.txt?

**Comment by vigonz06** [comment]
No eres tu, pero npi de por que

**Comment by vigonz06** [comment]
Creo que lo he solucionado, pero no puedo testear si falla sessionmenu

**Comment by vigonz06** [comment]
Esta hecho

**Comment by vigonz06** [comment]
Ahora si
