### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#15]
He añadido funcionalidad para borrar cuentas. (a362822107f432c12e1a90e0eb0ad1f69753263d)
Implementa la interfaz de usuario como mejor veas.

**Comment by vigonz06** [comment]
Estoy dudando entre:

Opción para borrar cuenta en sessionmenu

O bien

Al salir de tu cuenta, una opción para borrarla

Tu que ves mejor?

**Comment by vigonz06** [comment]
No tiene sentido que sea bool, dado qie la he situado en el session menú, por lo que ese usuario siempre va a existir, si no no podría estar en ese menú.
La pongo void si te parece bien

**Comment by vigonz06** [comment]
Tengo una excepción no controlada

**Comment by vigonz06** [comment]
En session menú, en la parte interna, he puesto que al borrar cuenta se salga del bucle, pues no huy session.

Pues bien, lo de que se salga lo he puesto igualando opt a 0, lo ejecuto, creo una cuenta, la borro, salgo de session, y hasta aquí todo bien, pero al querer salir del programa, en el main menú, me salta una excepción.

Se me acaba de ocurrir que no tenga que ver con los menús, si no con shut down, voy a ver

**Comment by vigonz06** [comment]
No es shutdown, lo he comprobado

**Comment by vigonz06** [comment]
Voy a intentar otra cosa

**Comment by vigonz06** [comment]
Quería intentar poner deleteaccount como posible opción al salir de tu sesión, pero aun así da error cuando quieres salir del main menu

**Comment by vigonz06** [comment]
Ahora no hay excepciones, pero maillist.deleite no hace lo que debiera, solo borra el primero de la lista

**Comment by Jsevillamol** [comment]
Olvide poner la variable del bucle dentor del bucle de borrado.
Ya debería funcionar.

**Comment by vigonz06** [comment]
Funciona

**Comment by vigonz06** [comment]
Ir works

Cierro por ahora
