### ISSUE TITLE
ContactList

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#17]
Al enviar un mail, de la misma manera que esta puesto por defecto el nombre 'Me' para mandartelo a ti mismo, añadir al menú una opción de que te deje guardar usuarios con nombres especificos

**Comment by Jsevillamol** [comment]
En Python sería trivial XD
Para este proyecto, habría que añadir un struct contacto, con campos de usuario y alias, y a la clase user una contact list.
No es difícil, y es una buena idea.
También habría que poner una manera de distinguir automáticamente entre un alias y una dirección. Esto se puede hacer buscando la arroba en lo introducido por user.

**Comment by vigonz06** [comment]
Tengo una función, que había puesto en graphinter, pero cambie a session, ya que no interactuaba con el usuario, que se encarga de verificar si lo que has puesto es un alias o un nombre, y para ello necesito un argumento de tipo user (he puesto session->getUser()), pero necesito sabes que ese usuario es el actual, el que esta en la cuenta, y no otro que se cree en el momento y por defecto, no se si me explico

**Comment by Jsevillamol** [comment]
He reestructurado el proyecto para acomodar una nueva clase, ContactList.
8d9e14a10b1dae746d14db12ecbacc22fe991227
Ahora es tu tarea hacer que todo funcione.

**Comment by vigonz06** [comment]
Formato: 
camino recorrido->siguiente función a ejecutarse

CreateAccount.sendMail.enterRecipients->contactlist.SearchFastName()

CreateAccount.AccountOptions->user.getContactlist()

CreateAccount.AliasOptions->user.getContactlist()

CreateAccount.Signout->contactlist.save()

Si no entiendes este formato dímelo, e intento explicarme mejor

**Comment by vigonz06** [comment]
Corrección en la ultima que puse (mismo formato)

CreateAccount.signout.exit->contactlist.save()

**Comment by vigonz06** [comment]
Una mas:

if (!fdimail.con_users.empty)
{
     fdimail.run->contactlist.load()
}

**Comment by Jsevillamol** [comment]
Supongo que lo que me has puesto son maneras de reproducir excepciones.
Aclaralo la próxima vez.

**Comment by vigonz06** [comment]
Lo que falla ahora básicamente es que en AliasOptions se muestra solo el alias, pero no el usuario, por lo que deduzco que no se esta guardando

A parte de que cuando introduces un alias nuevo no aparece en la lista de contactos, sin embargo luego si se guarda

Y por ultimo al sistema de guardado hay que tocarlo un poco, ya que en cierto momento, no se muy bien que hw hecho, pero me han aparecido un montón de 0 desordenados, no se que ha pasado

**Comment by vigonz06** [comment]
Ya funciona bien, y esta decorada, aun así, no cierro la issue, antes mejor repasarlo todo

**Comment by vigonz06** [comment]
De esta funciona todo, la cierro, a una mala se puede reabrir
