### ISSUE TITLE
Simplificando nombres

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#18]
Abro la issue de la que te hablaba por wa.

Mi idea es que puedas meter el nombre de usuario del destinatario, o bien completo, o bien solo el nombre, sin "@fdimail.com", y que detecte eso automáticamente.

Solo habría que añadir la comprobación de que el usuario no contuviera '@', y modificar un poco la función de comprobación, pero es mas sencillo, y tiene una capacidad ilimitada (eso a favor)
Aunque los nombres vendrían predefinidos, no podrías asignarlos tu (eso en contra)

Pero creo que compensa

**Comment by vigonz06** [comment]
Y bueno, el 'Me' seguiría quedándose por defecto como nombre rápido para mandartelo a ti mismo

**Comment by Jsevillamol** [comment]
Tal y como está la función de buscar un nombre rápido tiene tres caminos abiertos:
- Si detecta una @ no hace nada
- else if el nombre es un contacto, te devuelve la dirección asociada al mismo
- el se no hace nada.

Es cuestión de modificar el ultimo else para que te devuelva lo que has pasado + @fdimail.com

**Comment by vigonz06** [comment]
Se me ha ocurrido modificar la función de búsqueda de la @, o crear otra, de forma que puedas hacer tres cosas

O meter el alias asignado
O meter el nombre completo
O meter el nombre si el "@fdimail.com", y que lo añada solo
(El caso de "Me" seguiría siendo independiente)

**Comment by vigonz06** [comment]
Antes de hacer esto acabamos  lo de los alias

**Comment by Jsevillamol** [comment]
Me no debería ser independiente, sino un alias por defecto.
Como dijo Tim Peters:

> Special cases aren't special enough to break the rules

**Comment by vigonz06** [comment]
Ya, pero eso te limita un espacio de la lista, te lo reduce, a parte de que podrias borrarlo si quisieras, pero la idea es qie no se borre, y no limite la lista

Yo lo veo como la excepción qie confirma la regla

**Comment by vigonz06** [comment]
El controlador esta puesto, cierro esta issue
Seguimos discutiendo lo del Me en la otra issue
