### ISSUE TITLE
RecipientList

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#20]
Poner el sistema de múltiples destinatarios como otra lista

Esto estrictamente después de arreglar contactlist, y estrictamente en una branch, ya que bastante putada nos ha hecho contactlist

**Comment by vigonz06** [comment]
Aunque no se si tiene sentido, ya que los recipients no se almacenan

Si consideras que no tiene sentido, cierrala

**Comment by Jsevillamol** [comment]
Quieres decir qué incluyamos en mail un objeto subclase de lista que contenga los destinatarios?

**Comment by vigonz06** [comment]
Algo así, pero creo que no tiene sentido, porque cada correo tiene los destinatarios que elijas, y no se guardan, por lo que no tiene sentido, creo

**Comment by vigonz06** [comment]
Bueno, si, se guardan en el archivo de guardado de mails

Lo que tu consideres, pero antes arreglamos contacts

**Comment by vigonz06** [comment]
Creo que esta no, crear algo tan complejo como una lista para algo tan sencillo como el numero de destinatarios de un mail, me parece matar moscas a cañonazos

Aun así, no cierro la issue aun, antes dime si quieres hacerlo, o estas de acuerdo en dejarlo como esta

**Comment by vigonz06** [comment]
Por wa te he dicho que puede quedar bonito hacerlo, me refería a bonito a nivel de código, porque es verdad que a nivel de guardado se almacena donde debe, y a nivel de funcionalidad se hace lo que debe tal y como esta, pero a nivel de código puede quedar bonito hacerlo como una lista mas.
Yo diría que nos da tiempo

**Comment by vigonz06** [comment]
No se si funcionan los mecanismos o no, pero hay fallos que no tienen puto sentido

**Comment by Jsevillamol** [comment]
Cuanto más lo pienso, peor idea me parece. No tenemos que hacer operaciones complicadas con recipient list. Ni busquedas, ni insertar ni remover elementos,... No es necesario mantener una clase más si no va a aportar nueva funcionalidad.
Voy a cerrar la issue.
