### ISSUE TITLE
Ordenar inbox/outbox

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#24]
Tal vez haga falta o no. Yo dejo la issue abierta.

**Comment by Jsevillamol** [comment]
Copiado del enunciado:

> Lectura rápida de correos sin leer:
> Mostrará todos los correos sin leer de la bandeja correspondiente ordenados en primer lugar por >asunto y después por fecha. 
> OJO: Para ordenar por asunto debes ignorar los “Re: ” de los correos que 
> sean una respuesta.

**Comment by Jsevillamol** [comment]
De momento hay tres posibles órdenes: subject, date y emissor. Si se te ocurre alguno más dime.
Ahora a testear.

**Comment by vigonz06** [comment]
Hecho
