### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#26]
Varias cosas:

Lo que te he explicado del estatus de read sigue igual
Aclaracion: es extraxo que en outbox, incluso con asterisco fastread dice que no tienes mails sin leer

Excepción en delete account (solo si hay mails en esa cuenta)

Delete mails da excepción cuando no hay, o no quedan mails en la bandeja

Creo que es todo

**Comment by Jsevillamol** [comment]
Prueba ahora Fast Read 6fdbf8c8068678fddec16d07cd69180eee1da0ae

**Comment by Jsevillamol** [comment]
Delete Account Fix'd c1848c275dcdf6265b212d471c9c4b4d8dcff724
Testealo de nuevo pls.
No me explico cómo funcionaba antes, había un fallo gordo.

**Comment by Jsevillamol** [comment]
No consigo replicar la excepción de Delete Mails

**Comment by vigonz06** [comment]
Delete account funciona bien

**Comment by vigonz06** [comment]
Read pasa lo mismo, en outbox aparece el asterisco, y no se va hasta que no se va en inbox

**Comment by vigonz06** [comment]
Pasos para replicar la excepcion de deletemails:

Crear cuenta/iniciar sesión
Si la lista esta vacía, enviarte un mail
Opción de borrar mails
Borra todos los mails, uno a uno o todos juntos
Dale a delete all mails otra vez
Excepcion

**Comment by vigonz06** [comment]
Creo que he arreglado delwtemails
Simple cuestión de nomenclatura

**Comment by vigonz06** [comment]
Pues no, no esta arreglado, pero la excepción salta cuando estas en el menú de borrado, y le das a borrar todos cuando la lista esta vacia

**Comment by Jsevillamol** [comment]
Olvide linkar outbox cuando correspondía. Lo que ocurría es que outbox e inbox eran lo mismo. Sugiero testear desde varios usuarios en un futuro para obtener más info.
d56bbb1a8cf8e0f1051e95f626ce6fead392ca98

**Comment by Jsevillamol** [comment]
Oops. Dejé una excepción grave. Ya debería estar solucionada.
bf9c29a917ceb4135fc767965746cf3f8d08b7d6

**Comment by Jsevillamol** [comment]
Arreglado deleteMails. Las indicaciones fueron clave, buen trabajo.
7e4ac2f6d34fce29d8b2d8ec48effce49fe4313c

**Comment by vigonz06** [comment]
Lo de los read arreglado

**Comment by vigonz06** [comment]
Lo siento, pero delete sigue fallando

**Comment by Jsevillamol** [comment]
Tercer intento
2e7cf7aac3b8fa8b25543c00b31c168b4ffabe79

**Comment by vigonz06** [comment]
He añadido una cosa, pero ahora si funciona bien

**Comment by Jsevillamol** [comment]
Lovely. Cierro.
