### ISSUE TITLE
+bugs

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#28]
Si cambias tu usuario, te envías un mail a ti mismo, y lo borras, no se borra, sin embargo al volver a borrarlo salta una excepción

Al borrar tu cuenta solo se borran los mails a nombre de tu actual nombre de usuario, si tienes mails enviados por, o recibidos de tu anterior nombre, no se borran

**Comment by Jsevillamol** [comment]
Prueba ahora

**Comment by vigonz06** [comment]
El mail manual se borra

Pero al borrar cuenta los mails que están a tu antiguo nombre no se borran, solo reducen su usercount

**Comment by Jsevillamol** [comment]
Try again
e29e6401bda33e8bdabe71261e2fdd1b07ab9b5b

**Comment by vigonz06** [comment]
Se me olvido cerrar esta
