### ISSUE TITLE
Excepción en traylist::save()

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#31]
Sin hacer absolutamente nada, solo iniciar y cerrar el programa, al cerrarlo salta una excepción ahi

**Comment by Jsevillamol** [comment]
Me está volviendo loco esta cosa.
En algún momento desde que seleccionas exit y se llama al destructor de manager pasa algo con las inbox de los usuarios, pero no veo el qué.

**Comment by Jsevillamol** [comment]
Vamos avanzando. Dependiendo de si estabas en outbox o inbox al salir de la sesión se corrompe una cosa u otra.

**Comment by Jsevillamol** [comment]
Arreglado
