### ISSUE TITLE
Case insensitive

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#34]
Quiero que en las direcciones no distingamos entre minus y mayus.

**Comment by vigonz06** [comment]
Creo que tendría alguna idea de como hacerlo, pero me parece que no habria que hacerlo, mas que nada porque eso limita bastante los nombres a elegir, si jaime ya esta cogido, dices vale, voy a cogerme Jaime, y no te deja, creo que eso es algo muy típico entre los nombres de usuario, y lo estaríamos limitando

**Comment by Jsevillamol** [comment]
Quiero evitar que alguien se ponga de nombre de usuario DeStROyeR, y que el resto del mundo le den ganas de matarlo porque no hay quien se acuerde de que letras van en mayus y cuales en minus.

**Comment by vigonz06** [comment]
La verdad es que tiene sentido

**Comment by vigonz06** [comment]
Hecho
