### ISSUE TITLE
Correos por página

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#37]
Que se muestren 10 correos por página, y añadir una opción de pasar la página.
Así evitamos listas gigantescas en las que no se puede ver el primer correo.

**Comment by Jsevillamol** [comment]
Lista la lógica. Encárgate de la interfaz.

**Comment by vigonz06** [comment]
Ahora mismo tenemos 11 mails en la bandeja, pues bien, he puesto MAILS_X_PAGE a 5, de forma que deberian aparecer 3 págs con 5, 5, y 1 mails respectivamente
Pues solo aparecen 2 págs, y el ultimo mail, evidentemente, no aparece

Pongo esto aquí para ahorrarme una issue, cuantas menos mejor

**Comment by Jsevillamol** [comment]
Listo
