### ISSUE TITLE
ENTER key registering multiple times

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#39]
Un flush parece haber arreglado lo más grave, pero sigue ocurriendo cuando seleccionas Sign Out dentro de una sesión abierta.

**Comment by vigonz06** [comment]
Lo del flush que has puesto va a su bola, a veces lo toma como 1 vez, a veces como 2, creo reconocer un patrón, pero no lo he averiguado aun
(A veces me pasa lo mismo con escape, retrocede dos menús en vez de uno)

**Comment by vigonz06** [comment]
VK_RETURN y VK_SPACE me tienen asco, es la única explicacion

**Comment by Jsevillamol** [comment]
Me sigue pasando :cry:

**Comment by Jsevillamol** [comment]
Fix'd :v:
