### ISSUE TITLE
Error mail nunca se libera

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#40]
Los error mails nunca se liberan de la memoria

**Comment by Jsevillamol** [comment]
Solucionado.
He tenido que sacrificar un poco de funcionalidad a cambio, y los fallos se siguen manejando fatal.

**Comment by vigonz06** [comment]
No se si has terminado ya con esto, pero si es así, por favor cierra la issue, que cuantas mas issues abiertas mas nos agoviamos, porque parece que hay mas cosas que hacer (a mi al menos me pasa)

No la cierro, cierra la tu cuando acabes con ella

**Comment by Jsevillamol** [comment]
Sigue siendo una chapuza como manejamos los fallos...
La dejo abierta como un recordatorio de que falta testear qué ocurre cuando hay mails que no existem en las bandejas de los usuarios.

**Comment by Jsevillamol** [comment]
Excepciones everywhere cuando en la bandeja de un usuario hay mails que no existen en la base de datos.
Ya veré cómo tratamos con esto.

**Comment by vigonz06** [comment]
Es que creo que con los controladores que añadimos sencillamente no debería pasar, es decir, de ninguna forma puedes eliminar un mail de database sin eliminarlo de las inbox/outbox

**Comment by Jsevillamol** [comment]
Medio solucionado.
He puesto que no ponga en las trayList mails inexistentes durante el load.
Tendrá que valer.
