### ISSUE TITLE
Heap Corruption Error en VisibleTrayList resize()

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#43]
Ni idea acerca de dónde está el error. Salta después de FastRead.
Debe ser algún momento en el que escribimos en list[i], con i > dim, pero IDK

**Comment by vigonz06** [comment]
Es que creo que esta no hay que hacerla resize, porque startelem es 10, y lo máximo que abarca visible es 5, no?

**Comment by Jsevillamol** [comment]
Parece que no tiene nada que ver con los mails que empiezan por "re: ", como creía.
Solo ocurre en la primera página. Its nuts.

**Comment by Jsevillamol** [comment]
Lo he apañado.
Sigo mosqueado por saber qué ocurría antes del fix.
