### ISSUE TITLE
Enter trolling

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#46]
Si entras por primera vez al programa, y entras en tu cuenta, se va directamente a readmail (solo si entras al programa por primera vez)

**Comment by Jsevillamol** [comment]
Que significa entrar al programa por primera vez? Mail.txt y user.txt vacíos?

**Comment by vigonz06** [comment]
No
Explico:
Ejecutas el programa
Entras a tu cuenta, o creas cuenta
Y se va a readmail
Sales de tu cuenta, al menú principal
Vuelves a entrar, a la tuya o a otra
Y se queda en sessionmenu

**Comment by Jsevillamol** [comment]
No consigo replicar el fallo.
