### ISSUE TITLE
SelectAlias() fantasma

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#48]
En el archivo graphinter.h aparece la función selectalias().
Sin embargo en el correspondiente archivo.cpp, aparece como función de ámbito global, getContactlist, que se usa en selectalias, y eso ocurre porque selectalias no aparece en el buscador de graphinter.cpp, a pesar de estar implementada en el archivo

**Comment by Jsevillamol** [comment]
No entiendo qué intentas decirme.
selectAlias() es una función de GraphInter.
getContactList es un getter de User

**Comment by vigonz06** [comment]
A ver:
Ve a graphinter.cpp
Pon de filtro de búsqueda funciones de clase graphinter
Y en el buscador, busca selectalias()
Veras que no aparece
Y el getter getContactlist aparece como función de ámbito global en graphinter.cpp, precisamente por eso, porque selectalias no lo reconoce

**Comment by vigonz06** [comment]
No entiendo por que no lo reconoce, cuando esta definida en el respectivo header, esta bien implementada, y tiene el prefijo de su clase

**Comment by vigonz06** [comment]
En términos funcionales no da problemas, es solo que es raro que pase eso, pero si lo consideras irrelevante cierra la issue, como tu veas

**Comment by Jsevillamol** [comment]
Me está dejando esto patidifuso.
Es cierto que getContactList aparece como función global, pero no logro identificar el motivo.
Creo que voy a seguir el dicho de "if it ain't broken, don't fix it" y dejarlo como está.
