### ISSUE TITLE
Active list

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#5]
Cuando en la lista hay mas de 8 mensajes salta una excepción, creo que tiene que ver con assert(mail != nullptr)

**Comment by Jsevillamol** [comment]
Imposible. Assert interrumpe la ejecución de una manera muy distintiva.
Falta información (asumo que la excepción salta cuando intenta mostrar la bandeja de entrada/salida). Indica en qué función se produce la excepción (para verlo, dale a break y mira la pila de llamadas).

**Comment by Jsevillamol** [comment]
Se me ocurre que el fallo ocurra al llegar al límite maximo de mails.
EDIT: No es así. Cambiar las constantes globales no evita que surja la excepción.

**Comment by Jsevillamol** [comment]
No es así. Cambiar las constantes globales no evita que surja la excepción.

**Comment by vigonz06** [comment]
Con el ultimo commit que has hecho sobre esto va peor, ahora se queja solo con un mensaje

**Comment by vigonz06** [comment]
Sospecho de search
EDIT: no era eso

**Comment by vigonz06** [comment]
No era eso

**Comment by vigonz06** [comment]
Claro esta que el mail se hace nulo en algún sitio

**Comment by vigonz06** [comment]
Cuando sessionmenu coge los datos para mostrar el mail, no los encuentra, lo da como nulo

Lo extraño es que la inserción del mensaje en la bandeja no da errores, o sea que no es eso

**Comment by vigonz06** [comment]
Esta te la asigno a ti para cuando puedas, porque cada vez que toco algo lo empeoro, pero dada la posición en que los mails pasan a ser nulos, yo diría que el fallo esta en el algoritmo de List::search()

**Comment by vigonz06** [comment]
Esto sigue fallando, y yo sigo sin saber por que, miralo cuando tengas un ratillo, porfa

Creo que lo que hace fallar esto es lo mismo que hace fallar multyrecipiens

**Comment by vigonz06** [comment]
Solo falta arreglar esto, y ver si sigue fallando lo otro (multyrecipients)

**Comment by Jsevillamol** [comment]
El fallo no está en search, está en que los mails no se insertan donde deben.
Seguiré investigando.

**Comment by vigonz06** [comment]
Ahora salta el fallo cuando no hay mails en la bandeja, y eso que hay un controlador para eso

**Comment by vigonz06** [comment]
He creado un nuevo usuario y no salta el assert, o sea que lo mismo el problema esta en que he borrado los mensajes, pero active fray sigue diciendo que tiene mensajes 
EDIT: Efectivamente. Arreglado.

**Comment by vigonz06** [comment]
Efectivamente eso pasaba

**Comment by vigonz06** [comment]
Arreglado

**Comment by vigonz06** [comment]
Me estoy desesperando, ahora entras en tu mail y bien, pero haces cualquier cosa, y al volver al menú salta el assert
EDIT: No es al hacer cualquier cosa, es al mandar otro mail
EDIT: Solo te deja mandar un mail, al mandar el segundo, salta el assert
EDIT: Si borras el mail de activetray, y mandas otro si que te deja

**Comment by vigonz06** [comment]
No es al hacer cualquier cosa, es al mandar otro mail

**Comment by vigonz06** [comment]
Solo te deja mandar un mail, al mandar el segundo, salta el assert

**Comment by vigonz06** [comment]
Si borras el mail de activetray, y mandas otro si que te deja

**Comment by vigonz06** [comment]
No tengo ni idea qie que es lo que falla ahora

**Comment by vigonz06** [comment]
Search se come una vuelta, y no se por que

**Comment by vigonz06** [comment]
Ejecuto el programa
Accedo a mi cuenta
En ella tengo un correo en inbox y outbox (mandado a mi mismo)
Redacto otro enviado a mi mismo también

A partir de aquí:
Aclaración: he puesto puntos de parada en distintos sitios, entre otros en los tres casos posibles que abarca el bucle que contiene list::search(), para controlar dicha función.

Voy ejecutando paso a paso, hasta que el primer mail se muestra en la inbox/outbox
Y hago lo mismo con para el segundo
Cuando llego a search ocurre lo siguiente:

Vuelta 1:

left_key = 0
right_key = 1
pos = 0

Dentro del bucle:

evalúa el caso (getId == id)
pasa al siguiente
evalúa el caso getId < id
suma 1 a left_key

Vuelta 2:

left_key =  1
right_key = 1
pos = 1

Pero no da la segunda vuelta, y se va directamente a return nullptr en get(id)

**Comment by vigonz06** [comment]
Creo que acabo de ver el fallo

Apunte personal: 

traylist.inserta()
{
If (counter == MAX)
{
shiftleft(counter)
list[counter] = elem
}
else 
{
list[counter++]
}
}

Aclaración: en la versión actual el primer caso (if (counter == MAX)), la inserción del elemento en la lista amplia el contador en uno, cosa imposi ble de hacer ya que el array list no tiene mas capacidad

**Comment by vigonz06** [comment]
Aunque bueno, ese es un fallo, pero no creo que sea EL FALLO, ya que donde nos salta a nosotros, la lista no esta completa

**Comment by Jsevillamol** [comment]
Me precipité XD
Haz el testeo antes de cerrar, pero confío en que esté solucionado.
Lo arreglé en este commit: de3c4136d6b0ebe59ef601b5c73571d9834f48b4

**Comment by vigonz06** [comment]
Funciona, ahora bien, en search, la asignación de pos termina con dos (;), esta bien así, o sobra uno?

**Comment by vigonz06** [comment]
Cierro esta
