### ISSUE TITLE
Borrar body

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#6]
A ver si podemos encontrar una forma de borrar el body mas allá de los saltos de linea

**Comment by Jsevillamol** [comment]
Creo que quieres decir:
Borrar los saltos de línea adicionales que se introducen en el final de body.

**Comment by Jsevillamol** [comment]
Solución: poner la linea vacía como centinela. En la creación de mensake/carga se van leyendo lineas en un bucle hasta que se lee una linea vacía.

**Comment by vigonz06** [comment]
No me refería a eso, pero eso también es buena idea

**Comment by vigonz06** [comment]
Yo me refería a que cuando escribes en cuerpo del mensaje si decides saltar de linea, por lo que sea, y luego ves que te has equivocado y quieres borrar, el programa no te deja borrar mas que la ultima linea, si has puesto un salto de linea no puedes borrar lo que haya por encima, eso es lo que quiero arreglar, que te deje borrarlo todo

**Comment by vigonz06** [comment]
Para lo que tu has sugerido, como defino la linea vacía?

**Comment by vigonz06** [comment]
Se me ocurre

While(!linea vacía)
{
     getline(cin, this->body)
}
 Pero sigo sin saber como definir linea vacia

**Comment by Jsevillamol** [comment]
Mira mi último commit: 2b09dfc6e2bef8598c7a714327ce6e6223db1d79

**Comment by vigonz06** [comment]
Gracias
Voy a testear

**Comment by vigonz06** [comment]
El nuevo sistema de introduccion de texto en body esta bien, pero sigue sin poderse borrar el body tras un salto de linea

**Comment by Jsevillamol** [comment]
Y si lo implementamos de esta manera va a ser imposible. Pero no lo veo prioritario. Cierro la issue
