### ISSUE TITLE
Graphinter con sfml

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#7]
Si nos da tiempo, hacer la interfaz gráfica con sfml

**Comment by vigonz06** [comment]
Recalco el "si nos da tiempo", es decir, de la misma manera que en las anteriores practicas fue el modo 2P, el truco de cabo cañaveral, y el continúe mode, respectivamente, o sea, comenzar con ello, si da tiempo a hacerlo y que esté estable perfecto, si no se entrega la versión anterior.

También recalco lo señalado en la issue 'múltiples destinatarios' de que aquella tiene prioridad, pues venia en el enunciado como parte opcional

**Comment by vigonz06** [comment]
Bueno.... Yo no digo nada... Pero tenemos 11 diitas muy ricos para intentar ponernos con esto....

**Comment by vigonz06** [comment]
Podemos meterlo como parte opcional de la practica 5, ya que tenemos mas tiempo, y que la ampliación no es muy complicada

**Comment by vigonz06** [comment]
Claro esta que solo si nos da tiempo, el resto de lluvias de ideas tienen preferencia

**Comment by Jsevillamol** [comment]
Ya nada.
Para otro proyecto.
