### ISSUE TITLE
Primera letra perdida

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/fdimail#8]
Tras enviarme un mensaje a mi propia cuenta, desapareció la primera letra del Subject. ¿Alguna idea de qué puede causar el fallo?

**Comment by Jsevillamol** [comment]
![captura de pantalla 2](https://cloud.githubusercontent.com/assets/5825805/7350070/86cd5f8a-ecfd-11e4-9b1b-94c6beed9fc0.png)

Enviando un mensaje de jaime@fdimail a victor@fdimail se replica el fallo

**Comment by Jsevillamol** [comment]
No parece que el fallo ocurra al mostrar el mensaje.

**Comment by vigonz06** [comment]
Arreglado, puse un ignore donde no era
