### ISSUE TITLE
Ordenar active tray

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/fdimail#9]
Los últimos mensajes, entrantes y salientes, se situan al final de la bandeja, cuando deberian estar al principio.

Considero que primero habría que arreglar la excepción de activetray antes de ponerse con esto

**Comment by Jsevillamol** [comment]
Es tan fácil como recorrer inbox y outbox al revés en GraphInter::menu o la función que sea. Te dejo que te encargues

**Comment by vigonz06** [comment]
Perfecto, me ocupo en cuanto pueda

P.D.: como el fallo de active trsy tenga que ver con eso, y al cambiarlo se arregle me voy a reír mucho

**Comment by vigonz06** [comment]
Hecho, aunque el problema no era ese, siguen haciéndose nulos los mails

**Comment by vigonz06** [comment]
Aun así, ese problema es de otra issue, cierro esta
